#include <bits/stdc++.h>
using namespace std;

int main()
{
    string s="jgfafdabagaahhiigfdgefbeidcheiigbahadcfabcdcbgfdebebighiieidfbbiggcadgigfaghaaifdaaegfbcghaibibagegecdhifhgfdffedhdagfgiaigecgadcehgiaedihabfdeegdihgbdfeibcbfaaihegcgfaagdhfhbdhgigaibidegdfhiahhdhhcbibaeiccccegbddeabcgdehbhhfaedacbcfhiigbigdggfgebibebgegbfhchgdebiaibhdighdiedcaeifgffadifadeeiahbebbafddfeeeihiacgecbdgdiidhhaehacgidbfeichgccacaabiaihaifghcebaafgigccgdcebiciagbbfhehddidheihbgcahhhhbafdcfkuscqftowcyqcxehwtrnxrbuhcnbtmnfloqhumfynidijhorkuonmqidzvigxljmvsteoaminyakvnfsvyveweouxqcfwieo";
    cout<<s.size();
}